# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backend_pb2 as backend__pb2


class SDMS_BackendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/SDMS_Backend/Login',
                request_serializer=backend__pb2.LoginRequest.SerializeToString,
                response_deserializer=backend__pb2.LoginReply.FromString,
                )
        self.GetStudentDetails = channel.unary_unary(
                '/SDMS_Backend/GetStudentDetails',
                request_serializer=backend__pb2.IDRequest.SerializeToString,
                response_deserializer=backend__pb2.StudentDetailsReply.FromString,
                )
        self.GetStudentCourses = channel.unary_unary(
                '/SDMS_Backend/GetStudentCourses',
                request_serializer=backend__pb2.IDRequest.SerializeToString,
                response_deserializer=backend__pb2.CurrentCoursesReply.FromString,
                )
        self.GetCourseRequirements = channel.unary_unary(
                '/SDMS_Backend/GetCourseRequirements',
                request_serializer=backend__pb2.RequirementRequest.SerializeToString,
                response_deserializer=backend__pb2.RequirementReply.FromString,
                )
        self.GetCourses = channel.unary_unary(
                '/SDMS_Backend/GetCourses',
                request_serializer=backend__pb2.BrowseRequest.SerializeToString,
                response_deserializer=backend__pb2.BrowseReply.FromString,
                )
        self.SetStudentGrade = channel.unary_unary(
                '/SDMS_Backend/SetStudentGrade',
                request_serializer=backend__pb2.SetGradeRequest.SerializeToString,
                response_deserializer=backend__pb2.SetGradeReply.FromString,
                )
        self.SendEmail = channel.unary_unary(
                '/SDMS_Backend/SendEmail',
                request_serializer=backend__pb2.EmailRequest.SerializeToString,
                response_deserializer=backend__pb2.EmailReply.FromString,
                )


class SDMS_BackendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """rpc SayHello (HelloRequest) returns (HelloReply) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentDetails(self, request, context):
        """rpc GetGrade (GradeRequest) returns (GradeReply) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentCourses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourseRequirements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStudentGrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SDMS_BackendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=backend__pb2.LoginRequest.FromString,
                    response_serializer=backend__pb2.LoginReply.SerializeToString,
            ),
            'GetStudentDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentDetails,
                    request_deserializer=backend__pb2.IDRequest.FromString,
                    response_serializer=backend__pb2.StudentDetailsReply.SerializeToString,
            ),
            'GetStudentCourses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentCourses,
                    request_deserializer=backend__pb2.IDRequest.FromString,
                    response_serializer=backend__pb2.CurrentCoursesReply.SerializeToString,
            ),
            'GetCourseRequirements': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseRequirements,
                    request_deserializer=backend__pb2.RequirementRequest.FromString,
                    response_serializer=backend__pb2.RequirementReply.SerializeToString,
            ),
            'GetCourses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourses,
                    request_deserializer=backend__pb2.BrowseRequest.FromString,
                    response_serializer=backend__pb2.BrowseReply.SerializeToString,
            ),
            'SetStudentGrade': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStudentGrade,
                    request_deserializer=backend__pb2.SetGradeRequest.FromString,
                    response_serializer=backend__pb2.SetGradeReply.SerializeToString,
            ),
            'SendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=backend__pb2.EmailRequest.FromString,
                    response_serializer=backend__pb2.EmailReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SDMS_Backend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SDMS_Backend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SDMS_Backend/Login',
            backend__pb2.LoginRequest.SerializeToString,
            backend__pb2.LoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudentDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SDMS_Backend/GetStudentDetails',
            backend__pb2.IDRequest.SerializeToString,
            backend__pb2.StudentDetailsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStudentCourses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SDMS_Backend/GetStudentCourses',
            backend__pb2.IDRequest.SerializeToString,
            backend__pb2.CurrentCoursesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCourseRequirements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SDMS_Backend/GetCourseRequirements',
            backend__pb2.RequirementRequest.SerializeToString,
            backend__pb2.RequirementReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCourses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SDMS_Backend/GetCourses',
            backend__pb2.BrowseRequest.SerializeToString,
            backend__pb2.BrowseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStudentGrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SDMS_Backend/SetStudentGrade',
            backend__pb2.SetGradeRequest.SerializeToString,
            backend__pb2.SetGradeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SDMS_Backend/SendEmail',
            backend__pb2.EmailRequest.SerializeToString,
            backend__pb2.EmailReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
