/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: frontend.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as frontend_pb from './frontend_pb'; // proto import: "frontend.proto"


export class SDMS_BackendClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/SDMS_Backend/SayHello',
    grpcWeb.MethodType.UNARY,
    frontend_pb.HelloRequest,
    frontend_pb.HelloReply,
    (request: frontend_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    frontend_pb.HelloReply.deserializeBinary
  );

  sayHello(
    request: frontend_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontend_pb.HelloReply>;

  sayHello(
    request: frontend_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontend_pb.HelloReply) => void): grpcWeb.ClientReadableStream<frontend_pb.HelloReply>;

  sayHello(
    request: frontend_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontend_pb.HelloReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/SDMS_Backend/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/SDMS_Backend/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

  methodDescriptorGetGrade = new grpcWeb.MethodDescriptor(
    '/SDMS_Backend/GetGrade',
    grpcWeb.MethodType.UNARY,
    frontend_pb.GradeRequest,
    frontend_pb.GradeReply,
    (request: frontend_pb.GradeRequest) => {
      return request.serializeBinary();
    },
    frontend_pb.GradeReply.deserializeBinary
  );

  getGrade(
    request: frontend_pb.GradeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<frontend_pb.GradeReply>;

  getGrade(
    request: frontend_pb.GradeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontend_pb.GradeReply) => void): grpcWeb.ClientReadableStream<frontend_pb.GradeReply>;

  getGrade(
    request: frontend_pb.GradeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontend_pb.GradeReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/SDMS_Backend/GetGrade',
        request,
        metadata || {},
        this.methodDescriptorGetGrade,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/SDMS_Backend/GetGrade',
    request,
    metadata || {},
    this.methodDescriptorGetGrade);
  }

}

