# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbackend.proto\"+\n\tIDRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\xa5\x01\n\x13StudentDetailsReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x65mail_id\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64visor\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x65pt\x18\x05 \x01(\t\x12\x0e\n\x06\x64\x65gree\x18\x06 \x01(\t\x12\x0b\n\x03gpa\x18\x07 \x01(\t\x12\x10\n\x08grad_sem\x18\x08 \x01(\t\x12\x11\n\tgrad_year\x18\t \x01(\t2G\n\x0cSDMS_Backend\x12\x37\n\x11GetStudentDetails\x12\n.IDRequest\x1a\x14.StudentDetailsReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IDREQUEST']._serialized_start=17
  _globals['_IDREQUEST']._serialized_end=60
  _globals['_STUDENTDETAILSREPLY']._serialized_start=63
  _globals['_STUDENTDETAILSREPLY']._serialized_end=228
  _globals['_SDMS_BACKEND']._serialized_start=230
  _globals['_SDMS_BACKEND']._serialized_end=301
# @@protoc_insertion_point(module_scope)
